package com.example.car.repository;

import com.example.car.model.Car;
import org.apache.commons.collections.IteratorUtils;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;

import java.util.List;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

/**
 * Design Assumptions:
 * 1. We use Spring Data JPA.
 * 2. ID will be autogenerated
 * 3. Car is a model object
 * 4. We will use interfaces to interact with repository and use dependency injection while running
 * <p>
 * Requirements derived from higher-level tests (Contract tests in this case):
 * 1. Car has id, name and type (See: src/test/resources/contracts/car/shouldReturnCars.groovy)
 * 2. Should return all cars when queried.
 */
@DataJpaTest
public class CarRepositoryTest {

    @Autowired
    private CarRepository repository;

    @Autowired
    private TestEntityManager testEntityManager;

    @Test
    public void shouldAutoGenerateId()  {
        Car persistedCar = testEntityManager.persistFlushFind(new Car("prius", "hybrid"));
        assertThat(persistedCar.getId()).isNotNull();
    }

    @Test
    public void shouldReturnAllCarsWhenFindAll(){
        //arrange
        Car persistedCar1 = testEntityManager.persistFlushFind(new Car("prius", "hybrid"));
        Car persistedCar2 = testEntityManager.persistFlushFind(new Car("tesla", "electric"));

        //act
        Iterable<Car> returnedCars = repository.findAll();

        //assert
        List<Car> returnedCarList = IteratorUtils.toList(returnedCars.iterator());
        Car firstReturnedCar = returnedCarList.get(0);
        assertThat(firstReturnedCar.getId()).isNotNull();
        assertThat(firstReturnedCar.getId()).isEqualTo(persistedCar1.getId());
        assertThat(firstReturnedCar.getName()).isEqualTo(persistedCar1.getName());
        assertThat(firstReturnedCar.getType()).isEqualTo(persistedCar1.getType());

        Car secondReturnedCar = returnedCarList.get(1);
        assertThat(secondReturnedCar.getId()).isNotNull();
        assertThat(secondReturnedCar.getId()).isEqualTo(persistedCar2.getId());
        assertThat(secondReturnedCar.getName()).isEqualTo(persistedCar2.getName());
        assertThat(secondReturnedCar.getType()).isEqualTo(persistedCar2.getType());
    }
}
